# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [4]:
import numpy as np
np.zeros(100,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 2.Создать вектор размера 100, заполненный единицами

In [5]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### 3.Создать вектор размера 100, заполненный числом 3

In [6]:
np.full(100,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

#### 4. Как получить документацию о функции numpy.add из командной строки?

In [7]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 5. Поменять 2 строки в матрице

In [110]:
a = np.random.randint(1, 10, size=(3, 3))
print(a)
a[0],a[1]=a[1],a[0].copy()
a

[[4 1 7]
 [2 6 3]
 [6 6 6]]


array([[2, 6, 3],
       [4, 1, 7],
       [6, 6, 6]])

#### 6. Создать вектор со значениями от 10 до 100

In [22]:
np.arange(10,100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

#### 7. Развернуть вектор (первый становится последним)

In [109]:
a = np.random.randint(1, 10, 10)
print(a)
b = a[::-1]
b

[9 7 7 6 5 6 1 3 1 6]


array([6, 1, 3, 1, 6, 5, 6, 7, 7, 9])

#### 8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [21]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### 9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [108]:
a = np.arange(1,6)
b = a
for i in range(1,14,4):
    b = np.insert(b,i,[0,0,0])
b

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

#### 10. Создать 3x3 единичную матрицу

In [112]:
c = np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Создать массив 3x3x3 со случайными значениями

In [113]:
np.random.randint(1,100,(3,3,3))

array([[[74, 36, 20],
        [14, 57,  3],
        [22, 21,  4]],

       [[74, 77,  8],
        [26, 35, 69],
        [50, 78, 16]],

       [[33, 86,  4],
        [70, 61, 29],
        [13, 24, 50]]])

#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [114]:
a = np.random.randint(1,100,(10,10))
print(a)
print(a.min())
print(a.max())

[[59 46 88 41 92 88  7  3 53 69]
 [79 64 13 42 91 39 34 53 72 66]
 [68 15 72 48 58 23 58 42 72 32]
 [39 55 39 46 48  6 48 86 51 82]
 [73 91 93 66 95 83 12 24 28 63]
 [97 34 11 16 96 88 28 21 84 29]
 [ 1 86 67  9 64  5 33 45 24 71]
 [54  4 44 35 52 18 61 43  7 59]
 [15 86 73 40  9 27 44 14 26 89]
 [75 26 50 26 49 23 66 48 98 12]]
1
98


#### 13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [120]:
a = np.random.randint(1,10,30)
print(a)
print(np.mean(a))

[6 5 4 2 7 8 2 2 3 7 4 6 4 5 5 6 7 5 4 6 4 8 3 9 8 8 2 9 4 1]
5.133333333333334


#### 14. Создать матрицу с 0 внутри, и 1 на границах

In [121]:
a = np.ones((10,10), int)
a[1:-1,1:-1] = 0
a

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

#### 15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

In [327]:
a = np.random.randint(1,10, (3,3))
print(a)
a.resize(2,2,2)
a

[[4 9 9]
 [8 4 7]
 [9 2 6]]


array([[[4, 9],
        [9, 8]],

       [[4, 7],
        [9, 2]]])

#### 16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

In [128]:
a = np.diag([1,2,2,4],k=-1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 4, 0]])

#### 17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [166]:
a = np.zeros((8,8), dtype=int)
a[::2,::2] = 1
a[1::2,1::2] = 1
a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [167]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [168]:
np.tile(np.array([[1,0],[0,1]]),(4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 20. Перемножить матрицы 5x3 и 3x2

In [169]:
a = np.random.randint(1,10,(5,3))
b = np.random.randint(1,10,(3,2))
a.dot(b)

array([[141,  53],
       [158,  72],
       [ 93,  57],
       [147,  77],
       [ 36,  18]])

#### 21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [171]:
a = np.random.randint(1,10,(4,4))
print(a)
a[(a>3) & (a<8)] *= -1
a

[[1 8 1 4]
 [2 4 7 9]
 [1 4 5 1]
 [1 9 9 6]]


array([[ 1,  8,  1, -4],
       [ 2, -4, -7,  9],
       [ 1, -4, -5,  1],
       [ 1,  9,  9, -6]])

#### 23. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [172]:
np.tile(np.arange(5),(5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 24. Есть генератор, сделать с его помощью массив

In [176]:
m = int(input())
n = int(input())
[[i * j for j in range(n)] for i in range(m)]

3
4


[[0, 0, 0, 0], [0, 1, 2, 3], [0, 2, 4, 6]]

#### 25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [184]:
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 26. Отсортировать вектор

In [186]:
a = np.random.randint(1,100,10)
print(a)
a.sort()
a

[90 95 76 59 56 26 18 36 21  5]


array([ 5, 18, 21, 26, 36, 56, 59, 76, 90, 95])

#### 27. Проверить, одинаковы ли 2 numpy массива

In [189]:
a1 = np.random.randint(1,3,(2,2))
print(a1)
a2 = np.random.randint(1,3,(2,2))
print(a2)
result = np.allclose(a1,a2)
result

[[1 2]
 [2 2]]
[[1 1]
 [1 2]]


False

#### 28. Сделать массив неизменяемым

In [190]:
a = np.random.randint(1,3,(2,2))
a.flags.writeable = False

#### 29. Найти n наибольших значений в массиве

In [192]:
n = int(input())
a = np.random.randint(1,10,5)
a.sort()
print(a)
print(a[-n:])

2
[3 4 4 5 7]
[5 7]


#### 30. Заменить максимальный элемент на ноль

In [193]:
a = np.random.randint(1,10,(5,5))
print(a)
a[a==a.max()]=0
a

[[4 3 2 9 4]
 [5 7 9 1 9]
 [1 4 4 1 6]
 [8 5 8 2 2]
 [3 6 4 8 2]]


array([[4, 3, 2, 0, 4],
       [5, 7, 0, 1, 0],
       [1, 4, 4, 1, 6],
       [8, 5, 8, 2, 2],
       [3, 6, 4, 8, 2]])

#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [202]:
a = np.empty((5,5), [('x',float),('y',float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
a

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [209]:
a = (3,4)
b = (1,5)
c = 1 / np.subtract.outer(a, b)
c

array([[ 0.5       , -0.5       ],
       [ 0.33333333, -1.        ]])

#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [219]:
for dtype in [np.int8 ,np.uint8, np.int16, np.uint16, np.int32, np.uint32, np.int64, np.uint64]:
    print(dtype)
    print('min :', np.iinfo(dtype).min)
    print('max :', np.iinfo(dtype).max)
    print()
for dtype in [np.float16, np.float32, np.float64]:
    print(dtype)
    print('min :', np.finfo(dtype).min)
    print('max :', np.finfo(dtype).max)
    print()

<class 'numpy.int8'>
min : -128
max : 127

<class 'numpy.uint8'>
min : 0
max : 255

<class 'numpy.int16'>
min : -32768
max : 32767

<class 'numpy.uint16'>
min : 0
max : 65535

<class 'numpy.int32'>
min : -2147483648
max : 2147483647

<class 'numpy.uint32'>
min : 0
max : 4294967295

<class 'numpy.int64'>
min : -9223372036854775808
max : 9223372036854775807

<class 'numpy.uint64'>
min : 0
max : 18446744073709551615

<class 'numpy.float16'>
min : -65500.0
max : 65500.0

<class 'numpy.float32'>
min : -3.4028235e+38
max : 3.4028235e+38

<class 'numpy.float64'>
min : -1.7976931348623157e+308
max : 1.7976931348623157e+308



#### 34. Напечатать все значения в массиве

In [223]:
a = np.random.randint(1,10,(5,5))
print(np.ravel(a))

[8 4 3 5 8 1 4 4 6 1 6 7 2 4 8 4 4 5 7 2 3 1 7 4 3]


#### 35. Найти ближайшее к заданному значению число в заданном массиве

In [273]:
n = int(input())
a = np.random.randint(1,10,(3,3))
print(a)
min = np.abs(a-n).argmin()
print(np.ravel(a)[min])

2
[[1 7 9]
 [6 1 6]
 [4 3 2]]
2


#### 36. Преобразовать массив из float в int

In [272]:
a = np.random.random((3,3)) * 10
print(a)
a = a.astype(np.int32)
a

[[4.4845646  4.26500111 4.63112304]
 [4.38944576 6.30784181 4.59724091]
 [6.42185674 8.03337596 1.94022265]]


array([[4, 4, 4],
       [4, 6, 4],
       [6, 8, 1]])

#### 37. Каков эквивалент функции enumerate для numpy массивов?

In [266]:
a = np.array([[1, 2], [3, 4]])
for index, x in np.ndenumerate(a):
    print(index, x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


#### 38. Случайно расположить p элементов в 2D массив

In [274]:
p = int(input())
a = np.zeros((10,10), int)
np.put(a, np.random.choice(range(10 * 10), p), 1)
a

6


array([[0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

#### 39. Отнять среднее из каждой строки в матрице

In [277]:
a1 = np.random.randint(1,10,(3,3))
print(a1)
a2 = a1 - a1.mean(axis=1, keepdims=True)
a2

[[2 5 8]
 [3 8 9]
 [4 7 6]]


array([[-3.        ,  0.        ,  3.        ],
       [-3.66666667,  1.33333333,  2.33333333],
       [-1.66666667,  1.33333333,  0.33333333]])

#### 40. Отсортировать матрицу по n-ому столбцу

In [278]:
n = int(input())
a = np.random.randint(1,10,(5,5))
print(a)
print(a[a[:,n].argsort()])

3
[[3 3 9 5 7]
 [4 4 3 6 3]
 [1 8 3 5 2]
 [5 7 4 8 8]
 [2 1 4 8 8]]
[[3 3 9 5 7]
 [1 8 3 5 2]
 [4 4 3 6 3]
 [5 7 4 8 8]
 [2 1 4 8 8]]


#### 41. Определить, есть ли в 2D массиве нулевые столбцы

In [299]:
a = np.random.randint(0,2,(4,4))
print(a)
print((~a.any(axis=0)).any())

[[1 0 0 1]
 [0 0 1 1]
 [1 0 1 0]
 [0 0 0 1]]
True


#### 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [304]:
a = np.random.randint(1,5,[5, 5])
print(a)
b = np.random.randint(low=0, high=a.size, size=[5])
print(b)
a.flat[b] += 1
a

[[1 3 4 4 3]
 [4 2 1 2 2]
 [1 2 1 2 4]
 [1 4 1 3 4]
 [1 1 2 4 1]]
[20 22  3 15 15]


array([[1, 3, 4, 5, 3],
       [4, 2, 1, 2, 2],
       [1, 2, 1, 2, 4],
       [2, 4, 1, 3, 4],
       [2, 1, 3, 4, 1]])

#### 43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

#### 44. Дан четырехмерный массив, посчитать сумму по последним двум осям

In [330]:
a = np.random.randint(1,10, (2,2,2,2))
print(a)
sum = a.reshape(a.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[[[5 5]
   [4 7]]

  [[4 9]
   [9 8]]]


 [[[4 4]
   [7 2]]

  [[5 8]
   [4 8]]]]
[[21 30]
 [17 25]]
